name: t2t
description: Time to Train. Any Time. Any Where.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animations: ^2.0.2
  core:
    git:
      url: https://easycloud.codebasehq.com/mobile-apps/flpackages.git
      path: packages/core
    version: ^0.0.11
  dartz: ^0.10.0
  firebase_core: ^1.10.0
  firebase_auth: ^3.2.0
  flutter_bloc: ^8.0.0
  flutter_secure_storage: ^5.0.2
  freezed_annotation: ^1.0.0
  get_it: ^7.2.0
  google_fonts: ^2.2.0
  google_sign_in: ^5.2.1
  http: ^0.13.4
  injectable: ^1.5.0
  json_annotation: ^4.3.0
  firebase_crashlytics: ^2.3.0
  package_info: ^2.0.2
  loading_indicator: ^3.0.3
  shimmer: ^2.0.0
  rolling_switch: ^0.0.2
  get: ^4.6.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: null
  flutter_lints: ^1.0.0
  freezed: ^0.14.1+3
  json_serializable: ^6.0.1
  injectable_generator: ^1.5.2

flutter:

  uses-material-design: true

  fonts:
    - family: Conthrax
      fonts:
        - asset: assets/fonts/conthrax_sb.ttf
    - family: Convoy
      fonts:
        - asset: assets/fonts/convoy.ttf

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  #
  
  
